import React, { useEffect, useState } from "react";
import { ArrowLeft, Building2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { Badge, EmptyState, ErrorState, StatCard } from "../components/UI.jsx";
import { apiFetch } from "../context/api.js";

export function DepartmentDetail() {
  const { id } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState("");
  async function load() { try { setError(""); setData(await apiFetch(`/admin/departments/${id}`)); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, [id]);
  if (error && !data) return <ErrorState text={error} onRetry={load} />; if (!data) return <div className="skeleton-screen" />;
  return <div className="page-stack"><div className="action-row"><Link className="secondary-button" to="/admin/resources"><ArrowLeft size={16} /> All departments</Link></div><section className="welcome-banner"><div><span className="eyebrow">Admin department detail</span><h2>{data.department.name}</h2><p>Full operational view of the department.</p></div><div className="welcome-orb"><Building2 size={34} /></div></section><section className="stats-grid"><StatCard label="Students" value={data.students.length} hint="Assigned" tone="blue" /><StatCard label="Faculty" value={data.teachers.length} hint="Assigned" tone="green" /><StatCard label="Notices" value={data.notices.length} hint="Published" tone="amber" /><StatCard label="Complaints" value={data.complaints.length} hint="Department records" tone="red" /></section><section className="two-column"><div className="panel"><div className="section-heading"><div><span className="eyebrow">Leadership</span><h2>Head of department</h2></div></div>{data.hod ? <div className="list-row"><div><strong>{data.hod.name}</strong><span>{data.hod.email} · {data.hod.code}</span></div><Badge value="HOD" /></div> : <EmptyState title="HOD not assigned" text="Assign a faculty member from Department settings." />}</div><div className="panel"><div className="section-heading"><div><span className="eyebrow">Faculty</span><h2>Department faculty</h2></div></div>{data.teachers.length ? <div className="list-stack">{data.teachers.map((teacher) => <div className="list-row" key={teacher.id}><div><strong>{teacher.name}</strong><span>{teacher.email} · {teacher.code}</span></div><Badge value={teacher.id === data.department.hodId ? "HOD" : "Faculty"} /></div>)}</div> : <EmptyState title="No faculty records" text="No faculty is assigned to this department." />}</div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Students</span><h2>Department students</h2></div></div>{data.students.length ? <div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Email</th><th>Status</th></tr></thead><tbody>{data.students.map((student) => <tr key={student.id}><td><strong>{student.name}</strong><span>{student.rollNumber}</span></td><td>{student.className}</td><td>{student.email}</td><td><Badge value={student.approvalStatus || "approved"} /></td></tr>)}</tbody></table></div> : <EmptyState title="No students" text="No students are assigned to this department." />}</section></div>;
}
