import React, { useEffect, useMemo, useState } from "react";
import { BellRing, CreditCard, Save } from "lucide-react";
import { Badge, EmptyState, ErrorState, StatCard, useToast } from "../components/UI.jsx";
import { apiFetch } from "../context/api.js";
import { useAuth } from "../context/AuthContext.jsx";

const emptyForm = { academicYear: "2026-27", tuitionFee: 0, hostelFee: 0, examFee: 0, otherFee: 0, dueDate: "" };

export function FeesCenter() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const [data, setData] = useState(null); const [departments, setDepartments] = useState([]); const [notices, setNotices] = useState([]); const [selectedId, setSelectedId] = useState(""); const [form, setForm] = useState(emptyForm); const [notice, setNotice] = useState({ title: "", body: "", category: "fee", departmentId: "" }); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const { showToast } = useToast() || {};
  const [programs, setPrograms] = useState([]); const [programNotes, setProgramNotes] = useState(null); const [expandedProgramId, setExpandedProgramId] = useState("");
  const load = async () => { try { setError(""); const endpoint = isAdmin ? "/admin/fees" : "/hod/fees"; const [result, programData] = await Promise.all([apiFetch(endpoint), apiFetch("/fees/programs")]); setData(result); setPrograms(programData.programs || []); setProgramNotes(programData.notes || null); if (isAdmin) { const [departmentData, noticeData] = await Promise.all([apiFetch("/admin/departments"), apiFetch("/admin/notices")]); setDepartments(departmentData.departments || []); setNotices(noticeData.notices || []); if (!selectedId && departmentData.departments?.[0]) setSelectedId(departmentData.departments[0].id); } } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, [isAdmin]);
  useEffect(() => { const structure = isAdmin ? data?.structures?.find((item) => item.departmentId === selectedId) : data?.structure; if (structure) setForm(structure); }, [data, selectedId, isAdmin]);
  const filteredFees = useMemo(() => (data?.studentFees || []).filter((item) => `${item.studentName} ${item.rollNumber} ${item.department}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  async function saveStructure(event) { event.preventDefault(); const endpoint = isAdmin ? `/admin/fees/structures/${selectedId}` : "/hod/fees/structure"; await apiFetch(endpoint, { method: "PUT", body: JSON.stringify(form) }); showToast?.("Fee structure saved.", "success"); await load(); }
  async function remind(studentId) { await apiFetch(`/admin/fees/reminders/${studentId}`, { method: "POST" }); showToast?.("Fee reminder recorded and sent when SMTP is configured.", "success"); await load(); }
  async function publishNotice(event) { event.preventDefault(); await apiFetch("/admin/notices", { method: "POST", body: JSON.stringify(notice) }); setNotice({ title: "", body: "", category: "fee", departmentId: departments[0]?.id || "" }); showToast?.("Department notice published.", "success"); await load(); }
  if (error && !data) return <ErrorState text={error} onRetry={load} />; if (!data) return <div className="skeleton-screen" />;
  const selectedDepartment = departments.find((item) => item.id === selectedId);
  return <div className="page-stack">
    <section className="welcome-banner"><div><span className="eyebrow">Finance & communication</span><h2>{isAdmin ? "Fees and department notices" : "Department fees"}</h2><p>{isAdmin ? "Set department fee structures, review every student's balance, and send targeted notices." : `Review ${data.studentFees.length} students in your department and keep the fee plan current.`}</p></div><div className="welcome-orb"><CreditCard size={34} /></div></section>
    <section className="stats-grid"><StatCard label="Outstanding balance" value={`₹${Number(data.totals.due || 0).toLocaleString("en-IN")}`} hint="Across visible students" tone="red" /><StatCard label="Students with dues" value={data.totals.studentsWithDue} hint="Needs follow-up" tone="amber" /><StatCard label="Departments" value={isAdmin ? departments.length : "1"} hint="Fee scope" tone="blue" /><StatCard label="Reminder history" value={isAdmin ? data.totals.reminders : "—"} hint="Recorded reminders" tone="green" /></section>
    <section className="two-column">
      <div className="panel"><div className="section-heading"><div><span className="eyebrow">Fee structure</span><h2>{isAdmin ? selectedDepartment?.name || "Choose department" : "Department plan"}</h2></div><Badge value="Editable" /></div>{isAdmin && <label>Department<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<form className="admin-form" onSubmit={saveStructure}>{[["tuitionFee", "Tuition fee"], ["hostelFee", "Hostel fee"], ["examFee", "Examination fee"], ["otherFee", "Other fee"]].map(([key, label]) => <label key={key}>{label}<input type="number" min="0" value={form[key] || 0} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></label>)}<label>Academic year<input value={form.academicYear || ""} onChange={(e) => setForm({ ...form, academicYear: e.target.value })} /></label><label>Due date<input type="date" value={form.dueDate || ""} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label><button className="primary-button" type="submit"><Save size={17} /> Save fee structure</button></form></div>
      {isAdmin ? <div className="panel"><div className="section-heading"><div><span className="eyebrow">Department notice</span><h2>Send a notice</h2></div><BellRing size={19} /></div><form className="form-stack" onSubmit={publishNotice}><label>Department<select value={notice.departmentId || departments[0]?.id || ""} onChange={(e) => setNotice({ ...notice, departmentId: e.target.value })}>{departments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Title<input value={notice.title} onChange={(e) => setNotice({ ...notice, title: e.target.value })} required /></label><label>Message<textarea value={notice.body} onChange={(e) => setNotice({ ...notice, body: e.target.value })} required /></label><button className="primary-button" type="submit">Publish department notice</button></form>{notices.slice(0, 4).map((item) => <article className="notice-item" key={item.id}><strong>{item.title}</strong><span>{item.departmentName} · {new Date(item.createdAt).toLocaleDateString()}</span></article>)}</div> : <div className="panel"><div className="section-heading"><div><span className="eyebrow">HOD reminder</span><h2>Department follow-up</h2></div></div><p className="helper-text">HODs can see department-level balances here. Only administrators can send email reminders or edit individual payment records.</p></div>}
    </section>
    <section className="panel">
      <div className="section-heading"><div><span className="eyebrow">Published fee sheets</span><h2>Program-wise fees for {programs[0]?.academicYear || "2026-27"}</h2></div><Badge value={`${programs.length} programs`} /></div>
      {programNotes && <p className="helper-text">{programNotes.eligibility} · {programNotes.paymentSchedule} · {programNotes.dueDates}</p>}
      {programs.length ? <div className="table-wrap"><table><thead><tr><th>Program</th><th>Category</th><th>Semesters</th><th>Tuition / sem</th><th>Hostel / sem</th><th>Total (incl. one-time)</th></tr></thead><tbody>{programs.map((item) => <React.Fragment key={item.id}><tr onClick={() => setExpandedProgramId(expandedProgramId === item.id ? "" : item.id)} style={{ cursor: "pointer" }}><td><strong>{item.program}</strong></td><td>{item.category}</td><td>{item.semesters[0]?.semester}–{item.semesters[item.semesters.length - 1]?.semester}</td><td>₹{Number(item.semesters[0]?.tuitionFee || 0).toLocaleString("en-IN")}</td><td>₹{Number(item.semesters[0]?.hostelFee || 0).toLocaleString("en-IN")}</td><td><strong>₹{Number(item.totalFee).toLocaleString("en-IN")}</strong></td></tr>{expandedProgramId === item.id && <tr><td colSpan={6}><div className="table-wrap"><table><thead><tr><th>Semester</th><th>Tuition</th><th>Hostel</th><th>Exam</th><th>One-time charges</th><th>Semester total</th></tr></thead><tbody>{item.semesters.map((sem) => <tr key={sem.semester}><td>{sem.semester}</td><td>₹{sem.tuitionFee.toLocaleString("en-IN")}</td><td>₹{sem.hostelFee.toLocaleString("en-IN")}</td><td>₹{sem.examFee.toLocaleString("en-IN")}</td><td>₹{sem.oneTimeCharges.toLocaleString("en-IN")}</td><td>₹{sem.total.toLocaleString("en-IN")}</td></tr>)}</tbody></table></div><p className="helper-text">Transport fee: {item.transportFee}. One-time charges (application, uniform, Cambridge assessment) are billed with Semester {item.semesters[0]?.semester}.</p></td></tr>}</React.Fragment>)}</tbody></table></div> : <EmptyState title="No published fee sheets" text="Program fee sheets will appear once published." />}
    </section>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">Student fee ledger</span><h2>{isAdmin ? "All student details and dues" : "Department student dues"}</h2></div><Badge value={`${filteredFees.length} records`} /></div><label className="search-field full-width"><input placeholder="Search name, roll number, or department" value={query} onChange={(e) => setQuery(e.target.value)} /></label>{filteredFees.length ? <div className="table-wrap"><table><thead><tr><th>Student</th><th>Department</th><th>Total due</th><th>Paid</th><th>Balance</th><th>Status</th>{isAdmin && <th>Action</th>}</tr></thead><tbody>{filteredFees.map((item) => <tr key={item.id}><td><strong>{item.studentName}</strong><span>{item.rollNumber} · {item.email}</span></td><td>{item.department}</td><td>₹{Number(item.amountDue).toLocaleString("en-IN")}</td><td>₹{Number(item.amountPaid || 0).toLocaleString("en-IN")}</td><td><strong>₹{Number(item.balance).toLocaleString("en-IN")}</strong></td><td><Badge value={item.status} /></td>{isAdmin && <td>{item.balance > 0 && <button className="secondary-button" type="button" onClick={() => remind(item.studentId)}><BellRing size={15} /> Remind</button>}</td>}</tr>)}</tbody></table></div> : <EmptyState title="No fee records" text="Fee records will appear after departments and students are available." />}</section>
  </div>;
}
