import React, { useEffect, useState } from "react";
import { Megaphone, UsersRound } from "lucide-react";
import { Badge, EmptyState, ErrorState, StatCard } from "../components/UI.jsx";
import { apiFetch } from "../context/api.js";

export function HODCenter() {
  const [data, setData] = useState(null); const [form, setForm] = useState({ title: "", body: "", category: "academic" }); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setError(""); setData(await apiFetch("/hod/overview")); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  async function publish(event) { event.preventDefault(); try { await apiFetch("/hod/notices", { method: "POST", body: JSON.stringify(form) }); setForm({ title: "", body: "", category: "academic" }); setMessage("Department notice published."); await load(); } catch (err) { setError(err.message); } }
  async function updateComplaint(id, patch) { try { await apiFetch(`/hod/complaints/${id}`, { method: "PUT", body: JSON.stringify(patch) }); await load(); } catch (err) { setError(err.message); } }
  if (error && !data) return <ErrorState text={error} onRetry={load} />; if (!data) return <div className="skeleton-screen" />;
  return <div className="page-stack"><section className="welcome-banner"><div><span className="eyebrow">HOD department center</span><h2>{data.department.name}</h2><p>Manage your department's students, notices, faculty, and complaints.</p></div><div className="welcome-orb"><UsersRound size={34} /></div></section>{message && <div className="success-box">{message}</div>}{error && <div className="error-box">{error}</div>}
    <section className="stats-grid"><StatCard label="Students" value={data.students.length} hint="Department scope" tone="blue" /><StatCard label="Faculty" value={data.teachers.length} hint="Department staff" tone="green" /><StatCard label="Open complaints" value={data.complaints.filter((item) => item.status !== "resolved").length} hint="Needs attention" tone="red" /><StatCard label="Notices" value={data.notices.length} hint="Department notices" tone="amber" /></section>
    <section className="two-column"><div className="panel"><div className="section-heading"><div><span className="eyebrow">Communication</span><h2>Send department notice</h2></div><Megaphone size={19} /></div><form className="form-stack" onSubmit={publish}><label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="academic">Academic</option><option value="exam">Exam</option><option value="event">Event</option><option value="emergency">Emergency</option></select></label><label>Message<textarea value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} required /></label><button className="primary-button" type="submit">Publish notice</button></form></div><div className="panel"><div className="section-heading"><div><span className="eyebrow">Department notices</span><h2>Recent updates</h2></div></div>{data.notices.length ? <div className="notice-list">{data.notices.slice(0, 6).map((notice) => <article key={notice.id}><div className="notice-icon"><Megaphone size={16} /></div><div><strong>{notice.title}</strong><span>{notice.category} · {new Date(notice.createdAt).toLocaleString()}</span><p>{notice.body}</p></div></article>)}</div> : <EmptyState title="No notices yet" text="Your department notices will appear here." />}</div></section>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">Student directory</span><h2>Students in {data.department.name}</h2></div><Badge value={`${data.students.length} students`} /></div>{data.students.length ? <div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Email</th><th>Status</th></tr></thead><tbody>{data.students.map((student) => <tr key={student.id}><td><strong>{student.name}</strong><span>{student.rollNumber}</span></td><td>{student.className}</td><td>{student.email}</td><td><Badge value={student.approvalStatus} /></td></tr>)}</tbody></table></div> : <EmptyState title="No students" text="No student records are assigned to this department." />}</section>
    <section className="panel"><div className="section-heading"><div><span className="eyebrow">Casework</span><h2>Department complaints</h2></div><Badge value={`${data.complaints.length} total`} /></div>{data.complaints.length ? <div className="complaint-list">{data.complaints.map((complaint) => <article className="complaint-card" key={complaint.id}><div className="complaint-top"><div><strong>{complaint.title}</strong><span>{complaint.studentName} · {complaint.rollNumber}</span></div><Badge value={complaint.status} /></div><p>{complaint.description}</p><div className="admin-complaint-controls"><select value={complaint.status} onChange={(e) => updateComplaint(complaint.id, { status: e.target.value })}><option value="pending">Pending</option><option value="in-progress">In progress</option><option value="resolved">Resolved</option></select><textarea defaultValue={complaint.response || ""} placeholder="Response" onBlur={(e) => updateComplaint(complaint.id, { response: e.target.value })} /></div></article>)}</div> : <EmptyState title="No department complaints" text="Complaint records from your department students will appear here." />}</section>
  </div>;
}
