import React from "react";
import { ArrowRight, BookOpenCheck, ClipboardList, GraduationCap, ScanLine, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";

export function Home() {
  return (
    <main className="home-page">
      <nav className="home-nav">
        <div className="brand compact">
          <div className="brand-mark">
            <GraduationCap size={22} />
          </div>
          <strong>College Management Portal</strong>
        </div>
        <Link className="primary-button small" to="/login">
          Login
          <ArrowRight size={16} />
        </Link>
      </nav>
      <section className="hero-section">
        <div className="hero-copy">
          <span className="eyebrow">Full-stack portfolio project</span>
          <h1>College Management Portal</h1>
          <p>
            A responsive college operations portal with role-based dashboards, student approvals, attendance tracking,
            timetable management, complaints, reports, and hardware-ready attendance APIs.
          </p>
          <div className="hero-actions">
            <Link className="primary-button" to="/login">
              Open website
              <ArrowRight size={18} />
            </Link>
            <a className="secondary-button" href="#features">
              View features
            </a>
          </div>
        </div>
        <div className="hero-panel" aria-label="Attendance summary preview">
          <div className="scan-chip">
            <ScanLine size={22} />
            Portal sample
          </div>
          <div className="hero-card">
            <span>Data Structures</span>
            <strong>91%</strong>
            <small>31 present / 3 absent</small>
          </div>
          <div className="mini-grid">
            <div>Students</div>
            <div>Subjects</div>
            <Link className="mini-grid-link" to="/login" aria-label="Open Attendance">
              Attendance
            </Link>
            <div>Complaints</div>
          </div>
        </div>
      </section>
      <section id="features" className="feature-band">
        {[
          [ShieldCheck, "Role-based access", "Admin and student workflows are separated with JWT-protected routes."],
          [BookOpenCheck, "Smart attendance", "Interactive Question Panel and QR code-based attendance generated by teachers."],
          [ClipboardList, "Operations workflow", "Complaints, schedules, teachers, and reports are managed from focused dashboards."]
        ].map(([Icon, title, text]) => (
          <article className="feature-card" key={title}>
            <Icon size={24} />
            <h2>{title}</h2>
            <p>{text}</p>
          </article>
        ))}
      </section>
    </main>
  );
}
