import React, { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Clock3, QrCode, ShieldCheck } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { apiFetch } from "../context/api.js";
import { Badge, EmptyState } from "../components/UI.jsx";

export function QuizSession() {
  const { id } = useParams(); const navigate = useNavigate(); const [session, setSession] = useState(null); const [error, setError] = useState("");
  useEffect(() => { apiFetch(`/shared/quiz-session/${id}`).then((data) => setSession(data.session)).catch((err) => setError(err.message)); }, [id]);
  if (error) return <div className="page-stack"><div className="error-box">{error}</div><button className="secondary-button" onClick={() => navigate("/student")}>Back to student panel</button></div>;
  if (!session) return <div className="loading-panel">Opening classroom question session…</div>;
  return <div className="page-stack student-quiz-session"><section className="attendance-hero"><div><span className="eyebrow">Live classroom / verified question</span><h2>{session.title}</h2><p>{session.subjectName} · {session.className} · started by {session.teacherName}</p></div><div className="live-indicator"><i /> Live until {new Date(session.endsAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</div></section><section className="panel session-instructions"><ShieldCheck size={19} /><div><strong>One secure path from QR to question</strong><span>You are signed in as a student in this class. Open an unanswered question below, answer it, and allow location access when submitting attendance.</span></div></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Questions from your faculty</span><h2>{session.questions.length} available</h2></div><QrCode size={19} /></div>{session.questions.length ? <div className="student-question-list">{session.questions.map((question, index) => <button className={`student-question-card ${question.attempted ? "attempted" : ""}`} key={question.id} disabled={question.attempted} onClick={() => navigate(`/student/quiz/${question.id}`)}><span className="question-number">{index + 1}</span><div><strong>{question.question}</strong><span>{question.attempted ? "Submitted · attendance result recorded" : `${question.options.length} answer choices · tap to open`}</span></div>{question.attempted ? <CheckCircle2 size={19} /> : <ArrowRight size={19} />}{question.attempted && <Badge value="completed" />}</button>)}</div> : <EmptyState title="Your faculty is preparing the question" text="Keep this page open and refresh in a moment." />}</section><button className="ghost-button" onClick={() => navigate("/student")}>Back to student panel</button></div>;
}
