import React, { useEffect, useMemo, useState } from "react";
import { ExternalLink, Plus, QrCode, Send, Square, XCircle } from "lucide-react";
import { apiFetch } from "../context/api.js";
import { Badge, EmptyState } from "../components/UI.jsx";

<<<<<<< HEAD
const emptyQuestion = { question: "", answerType: "written", options: ["", "", "", ""], correctAnswerIndex: 0 };
=======
const emptyQuestion = { question: "", options: ["", "", "", ""], correctAnswerIndex: 0 };
>>>>>>> 78613d2d2ecc9f02e71d4658e00f2f6e7ccc4cdc

export function QuizGenerator() {
  const [sessions, setSessions] = useState([]); const [classes, setClasses] = useState([]); const [subjects, setSubjects] = useState([]); const [selectedId, setSelectedId] = useState(""); const [form, setForm] = useState({ className: "", subjectId: "", title: "", durationMinutes: 30 }); const [question, setQuestion] = useState(emptyQuestion); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setError(""); const [sessionData, studentData, subjectData] = await Promise.all([apiFetch("/faculty/quiz-sessions"), apiFetch("/faculty/students"), apiFetch("/subjects")]); setSessions(sessionData.sessions || []); setClasses(studentData.classes || []); setSubjects(subjectData.subjects || []); if (!form.className && studentData.classes?.length) setForm((prev) => ({ ...prev, className: studentData.classes[0] })); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const current = useMemo(() => sessions.find((session) => session.id === selectedId) || sessions[0], [sessions, selectedId]);
  useEffect(() => { if (!selectedId && sessions[0]) setSelectedId(sessions[0].id); }, [sessions, selectedId]);
  async function startSession(event) { event.preventDefault(); try { const data = await apiFetch("/faculty/quiz-sessions", { method: "POST", body: JSON.stringify(form) }); setMessage("Live question session started. Display the QR on the classroom desktop."); setSelectedId(data.session.id); setForm((prev) => ({ ...prev, title: "" })); await load(); } catch (err) { setError(err.message); } }
  async function addQuestion(event) { event.preventDefault(); if (!current) return; try { await apiFetch(`/faculty/quiz-sessions/${current.id}/questions`, { method: "POST", body: JSON.stringify(question) }); setQuestion(emptyQuestion); setMessage("Question added to the live session."); await load(); } catch (err) { setError(err.message); } }
  async function closeSession() { if (!current) return; try { await apiFetch(`/faculty/quiz-sessions/${current.id}/toggle`, { method: "PUT" }); await load(); } catch (err) { setError(err.message); } }
  const sessionUrl = current ? `${window.location.origin}/student/quiz-session/${current.id}` : "";
  const qrUrl = sessionUrl ? `https://api.qrserver.com/v1/create-qr-code/?size=420x420&margin=18&data=${encodeURIComponent(sessionUrl)}` : "";
  if (loading) return <div className="loading-panel">Loading faculty question sessions…</div>;
  return <div className="page-stack quiz-workspace">
    <section className="attendance-hero"><div><span className="eyebrow">Faculty workspace / live classroom</span><h2>QR question sessions</h2><p>Start one class session, display its QR code on the desktop, and add one or more attendance questions while students join.</p></div><div className="live-indicator"><i /> {current?.active ? "Session control ready" : "No live session"}</div></section>
    {error && <div className="warning-banner"><XCircle size={18} /> {error}</div>}{message && <div className="success-box"><Send size={17} /> {message}</div>}
    <div className="two-column quiz-layout"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Step 1</span><h2>Start a class session</h2></div><QrCode size={20} color="var(--blue)" /></div><form onSubmit={startSession} className="form-stack"><label>Class<select value={form.className} onChange={(e) => setForm({ ...form, className: e.target.value, subjectId: "" })} required>{classes.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Subject<select value={form.subjectId} onChange={(e) => setForm({ ...form, subjectId: e.target.value })} required><option value="">Select subject</option>{subjects.filter((subject) => subject.className === form.className).map((subject) => <option key={subject.id} value={subject.id}>{subject.subjectName} ({subject.code})</option>)}</select></label><label>Session title <input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Week 4 participation check" /></label><label>Duration (minutes)<input type="number" min="5" max="180" value={form.durationMinutes} onChange={(e) => setForm({ ...form, durationMinutes: e.target.value })} /></label><button className="primary-button" type="submit"><QrCode size={16} /> Start and show QR</button></form><div className="session-picker"><span className="eyebrow">Previous sessions</span>{sessions.length ? sessions.map((session) => <button key={session.id} className={session.id === current?.id ? "selected-session" : ""} onClick={() => setSelectedId(session.id)}><span>{session.title}</span><Badge value={session.active ? "live" : "closed"} /></button>) : <p className="muted">No sessions started yet.</p>}</div></section>
    <section className="panel qr-stage">{current ? <><div className="section-heading"><div><span className="eyebrow">Step 2 · Display on desktop</span><h2>{current.title}</h2><p className="muted">{current.className} · {current.questions?.length || 0} question{current.questions?.length === 1 ? "" : "s"}</p></div><Badge value={current.active ? "live" : "closed"} /></div><div className="qr-frame"><img src={qrUrl} alt="QR code for the live student question session" /><strong>Scan to join the question</strong><span>Students will be asked to log in, then returned directly to this session.</span></div><div className="qr-url"><span>{sessionUrl}</span><button className="ghost-button small" onClick={() => navigator.clipboard?.writeText(sessionUrl)}><ExternalLink size={14} /> Copy link</button></div><button className="secondary-button full" onClick={closeSession} disabled={!current.active}><Square size={14} /> {current.active ? "Close session" : "Session closed"}</button></> : <EmptyState title="Start a session to generate its QR" text="The QR code will remain visible here for the classroom desktop." />}</section></div>
<<<<<<< HEAD
    {current?.active && <section className="panel"><div className="section-heading"><div><span className="eyebrow">Step 3</span><h2>Add questions to this session</h2></div><Plus size={20} color="var(--blue)" /></div><form onSubmit={addQuestion} className="question-builder"><label className="span-two">Question<input value={question.question} onChange={(e) => setQuestion({ ...question, question: e.target.value })} required placeholder="What should students answer?" /></label><label className="span-two">Response type<select value={question.answerType} onChange={(e) => setQuestion({ ...question, answerType: e.target.value })}><option value="written">Written answer</option><option value="choice">Multiple choice</option></select></label>{question.answerType === "choice" && question.options.map((option, index) => <label key={index}>Option {index + 1}<div className="option-input"><input value={option} onChange={(e) => setQuestion({ ...question, options: question.options.map((item, itemIndex) => itemIndex === index ? e.target.value : item) })} required /><input className="correct-radio" type="radio" name="correctAnswer" checked={question.correctAnswerIndex === index} onChange={() => setQuestion({ ...question, correctAnswerIndex: index })} title="Correct answer" /></div></label>)}<button className="primary-button" type="submit"><Plus size={16} /> Add question</button></form>{current.questions?.length ? <div className="question-list">{current.questions.map((item, index) => <div className="question-item" key={item.id}><span className="question-number">{index + 1}</span><div><strong>{item.question}</strong><span>{item.answerType === "written" ? "Written response · campus verification required" : `${item.options.length} answer choices · correct answer is protected`}</span></div></div>)}</div> : <EmptyState title="No questions yet" text="Add the first question. Students who join through the QR will see it immediately." />}</section>}
=======
    {current?.active && <section className="panel"><div className="section-heading"><div><span className="eyebrow">Step 3</span><h2>Add questions to this session</h2></div><Plus size={20} color="var(--blue)" /></div><form onSubmit={addQuestion} className="question-builder"><label className="span-two">Question<input value={question.question} onChange={(e) => setQuestion({ ...question, question: e.target.value })} required placeholder="What should students answer?" /></label>{question.options.map((option, index) => <label key={index}>Option {index + 1}<div className="option-input"><input value={option} onChange={(e) => setQuestion({ ...question, options: question.options.map((item, itemIndex) => itemIndex === index ? e.target.value : item) })} required /><input className="correct-radio" type="radio" name="correctAnswer" checked={question.correctAnswerIndex === index} onChange={() => setQuestion({ ...question, correctAnswerIndex: index })} title="Correct answer" /></div></label>)}<button className="primary-button" type="submit"><Plus size={16} /> Add question</button></form>{current.questions?.length ? <div className="question-list">{current.questions.map((item, index) => <div className="question-item" key={item.id}><span className="question-number">{index + 1}</span><div><strong>{item.question}</strong><span>{item.options.length} answer choices · correct answer is protected</span></div></div>)}</div> : <EmptyState title="No questions yet" text="Add the first question. Students who join through the QR will see it immediately." />}</section>}
>>>>>>> 78613d2d2ecc9f02e71d4658e00f2f6e7ccc4cdc
  </div>;
}
