import React, { useEffect, useState } from "react";
import { Filter, ShieldAlert } from "lucide-react";
import { Badge, DashboardSkeleton, EmptyState, StatCard } from "../components/UI.jsx";
import { apiFetch } from "../context/api.js";

export function SecurityDashboard() { const [data, setData] = useState(null); const [filters, setFilters] = useState({ from: "", to: "", user: "", eventType: "", severity: "" }); const [error, setError] = useState("");
  async function load() { try { setError(""); const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); setData(await apiFetch(`/admin/security?${query}`)); } catch (err) { setError(err.message); } }
  useEffect(() => { load(); }, []);
  if (!data && !error) return <DashboardSkeleton />;
  return <div className="page-stack"><section className="panel"><div className="section-heading"><div><span className="eyebrow">Admin only</span><h2>Security dashboard</h2><p className="helper-text">Monitor authentication, sessions, suspicious activity, and sensitive API actions.</p></div><ShieldAlert size={22} /></div>{error && <div className="error-box">{error}</div>}<div className="filter-grid"><label>From<input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} /></label><label>To<input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} /></label><label>User or target<input placeholder="ID or resource" value={filters.user} onChange={(e) => setFilters({ ...filters, user: e.target.value })} /></label><label>Event type<input placeholder="auth.login" value={filters.eventType} onChange={(e) => setFilters({ ...filters, eventType: e.target.value })} /></label><label>Severity<select value={filters.severity} onChange={(e) => setFilters({ ...filters, severity: e.target.value })}><option value="">All severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></label><button className="primary-button" type="button" onClick={load}><Filter size={16} /> Apply filters</button></div></section>{data && <><section className="stats-grid"><StatCard label="Failed logins" value={data.summary.failedLoginAttempts} hint="Authentication failures" tone="red" /><StatCard label="Active sessions" value={data.summary.activeSessions} hint="Refresh tokens" tone="blue" /><StatCard label="Recent logins" value={data.summary.recentLogins} hint="Recorded successes" tone="green" /><StatCard label="Suspicious activity" value={data.summary.suspiciousActivity} hint="Failed or critical events" tone="amber" /><StatCard label="Account lockouts" value={data.summary.accountLockouts} hint="Rate-limit events" tone="red" /></section><section className="panel"><div className="section-heading"><div><span className="eyebrow">Immutable history</span><h2>Audit logs</h2></div><Badge value={`${data.total} matching`} /></div>{data.auditLogs.length ? <div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>User</th><th>Target</th><th>Status</th><th>IP / client</th></tr></thead><tbody>{data.auditLogs.map((item) => <tr key={item.id}><td>{new Date(item.timestamp).toLocaleString()}</td><td><strong>{item.action}</strong><span>{item.role || "anonymous"}</span></td><td>{item.userId || "Anonymous"}</td><td>{item.target || "-"}</td><td><Badge value={item.success ? item.severity : `failed · ${item.severity}`} /></td><td>{item.ip}<span>{item.userAgent?.slice(0, 42)}</span></td></tr>)}</tbody></table></div> : <EmptyState title="No matching security events" text="Try broader filters or wait for new activity." />}</section></>}</div>; }
