import { Router } from "express";
import crypto from "node:crypto";
import { readDb, writeDb, makeId } from "../db/fileStore.js";
import { requireAuth, requireStaff } from "../middleware/auth.js";
import { clientKey, rateConfig, rateLimit } from "../middleware/rateLimit.js";
import { calculateStudentStats, enrichAttendance, subjectStats, today, upsertAttendance, ATTENDANCE_STATUSES, createQrToken, attendanceAnalytics, attendanceCsv } from "../services/attendanceService.js";
import { classesTaughtByTeacher, studentIdsVisibleToTeacher } from "../services/accessService.js";
import { isWithinCollege } from "../utils/geo.js";

export const attendanceRouter = Router();
function parseDateParam(value) { if (value === undefined || value === null || value === "") return { date: null, valid: true }; if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(new Date(value).getTime())) return { date: null, valid: false }; return { date: value, valid: true }; }
function canAccessSubject(db, req, subject) { return req.user.role === "admin" || (req.user.role === "teacher" && classesTaughtByTeacher(db, req.user.code).includes(subject?.className)); }
function timeInWindow(session) { const now = Date.now(); return now >= new Date(session.startsAt).getTime() && now <= new Date(session.endsAt).getTime(); }

attendanceRouter.get("/", requireAuth, async (req, res) => { const db = await readDb(); let records = db.attendance || []; if (req.user.role === "teacher") { const visible = studentIdsVisibleToTeacher(db, req.user.code); records = records.filter((item) => visible.has(item.studentId)); } if (req.query.studentId) records = records.filter((item) => item.studentId === req.query.studentId); if (req.query.subjectId) records = records.filter((item) => item.subjectId === req.query.subjectId); if (req.query.date) records = records.filter((item) => item.date === req.query.date); if (req.user.role === "student") records = records.filter((item) => item.studentId === req.user.id); res.json({ attendance: enrichAttendance(records, db) }); });
attendanceRouter.get("/summary", requireAuth, async (req, res) => { const db = await readDb(); const visible = req.user.role === "teacher" ? studentIdsVisibleToTeacher(db, req.user.code) : null; const studentId = req.user.role === "student" ? req.user.id : req.query.studentId; if (req.user.role === "teacher" && studentId && !visible.has(studentId)) return res.status(403).json({ message: "You can only view attendance for students in your classes." }); if (studentId) return res.json({ stats: calculateStudentStats(studentId, db.attendance || []), subjects: subjectStats(studentId, db.subjects, db.attendance || []), today: enrichAttendance((db.attendance || []).filter((i) => i.studentId === studentId && i.date === today()), db) }); const scoped = req.user.role === "teacher" ? (db.attendance || []).filter((i) => visible.has(i.studentId)) : (db.attendance || []); const present = scoped.filter((i) => ["present", "late"].includes(i.status)).length; res.json({ stats: { students: req.user.role === "teacher" ? visible.size : db.students.length, subjects: db.subjects.length, present, absent: scoped.filter((i) => i.status === "absent").length, percentage: scoped.length ? Math.round((present / scoped.length) * 100) : 0 }, today: enrichAttendance(scoped.filter((i) => i.date === today()), db) }); });

attendanceRouter.get("/roster", requireAuth, requireStaff, async (req, res) => { const { subjectId } = req.query; if (!subjectId) return res.status(400).json({ message: "subjectId is required." }); const parsed = parseDateParam(req.query.date); if (!parsed.valid) return res.status(400).json({ message: "date must be a valid date in YYYY-MM-DD format." }); const db = await readDb(); const subject = db.subjects.find((i) => i.id === subjectId); if (!subject) return res.status(404).json({ message: "Subject not found." }); if (!canAccessSubject(db, req, subject)) return res.status(403).json({ message: "You can only mark attendance for classes you teach." }); const date = parsed.date || today(); const roster = db.students.filter((s) => s.className === subject.className).map((student) => { const existing = db.attendance.find((i) => i.studentId === student.id && i.subjectId === subject.id && i.date === date); return { studentId: student.id, name: student.name, rollNumber: student.rollNumber, status: existing?.status || null, time: existing?.time || null, method: existing?.method || null, riskLevel: existing?.riskLevel || "low" }; }); res.json({ subject: { id: subject.id, subjectName: subject.subjectName, code: subject.code, className: subject.className }, date, roster }); });

attendanceRouter.post("/mark", requireAuth, requireStaff, rateLimit({ ...rateConfig("ATTENDANCE_MARK", { windowMs: 60000, limit: 100 }), message: "Too many attendance updates.", keyGenerator: (req) => req.user?.id || clientKey(req) }), async (req, res) => { const { studentId, subjectId, status, date, reason } = req.body || {}; if (!studentId || !subjectId || !ATTENDANCE_STATUSES.includes(status)) return res.status(400).json({ message: `studentId, subjectId, and a status of ${ATTENDANCE_STATUSES.join(", ")} are required.` }); const parsed = parseDateParam(date); if (!parsed.valid) return res.status(400).json({ message: "date must be a valid date in YYYY-MM-DD format." }); const db = await readDb(); const student = db.students.find((i) => i.id === studentId); const subject = db.subjects.find((i) => i.id === subjectId); if (!student || !subject) return res.status(404).json({ message: "Student or subject not found." }); if (student.className !== subject.className) return res.status(400).json({ message: "This student is not enrolled in this subject's class." }); if (!canAccessSubject(db, req, subject)) return res.status(403).json({ message: "You can only mark attendance for classes you teach." }); const result = upsertAttendance(db, { studentId, subjectId, status, date: parsed.date, method: "manual", changedBy: req.user.id, reason }); await writeDb(db); res.json({ record: enrichAttendance([result.record], db)[0], duplicatePrevented: result.duplicatePrevented }); });

attendanceRouter.post("/batch", requireAuth, requireStaff, async (req, res) => { const { subjectId, date, records, idempotencyKey } = req.body || {}; if (!subjectId || !Array.isArray(records) || !records.length || !idempotencyKey) return res.status(400).json({ message: "subjectId, records, and idempotencyKey are required." }); const parsed = parseDateParam(date); if (!parsed.valid) return res.status(400).json({ message: "date must be valid YYYY-MM-DD." }); const db = await readDb(); db.attendanceBatches ||= {}; if (db.attendanceBatches[idempotencyKey]) return res.json({ ...db.attendanceBatches[idempotencyKey], replayed: true }); const subject = db.subjects.find((i) => i.id === subjectId); if (!subject || !canAccessSubject(db, req, subject)) return res.status(403).json({ message: "You cannot mark this subject." }); const results = records.map((item) => { const student = db.students.find((s) => s.id === item.studentId); if (!student || student.className !== subject.className || !ATTENDANCE_STATUSES.includes(item.status)) return { studentId: item.studentId, error: "Invalid student or status" }; return upsertAttendance(db, { studentId: student.id, subjectId, status: item.status, date: parsed.date, method: "bulk", changedBy: req.user.id }); }); const response = { batchId: makeId("batch"), processed: results.filter((i) => !i.error).length, rejected: results.filter((i) => i.error).length, records: results.map((i) => i.record ? enrichAttendance([i.record], db)[0] : i) }; db.attendanceBatches[idempotencyKey] = response; await writeDb(db); res.status(201).json(response); });

attendanceRouter.post("/sessions", requireAuth, requireStaff, async (req, res) => { const { subjectId, durationMinutes = 15, startsAt = new Date().toISOString(), lateAfterMinutes = 5 } = req.body || {}; const db = await readDb(); const subject = db.subjects.find((i) => i.id === subjectId); if (!subject || !canAccessSubject(db, req, subject)) return res.status(403).json({ message: "You cannot create a session for this subject." }); const starts = new Date(startsAt); const session = { id: makeId("session"), subjectId, createdBy: req.user.id, startsAt: starts.toISOString(), endsAt: new Date(starts.getTime() + Number(durationMinutes) * 60000).toISOString(), lateAfterMinutes: Number(lateAfterMinutes) || 5, sequence: 0, qrToken: createQrToken("new"), active: true, createdAt: new Date().toISOString() }; session.qrToken = createQrToken(session.id, session.sequence); db.attendanceSessions ||= []; db.attendanceSessions.unshift(session); await writeDb(db); res.status(201).json({ session }); });
attendanceRouter.get("/sessions", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); const sessions = (db.attendanceSessions || []).filter((s) => req.user.role === "admin" || s.createdBy === req.user.id).map((s) => ({ ...s, qr: `attendance://${s.id}?token=${s.qrToken}` })); res.json({ sessions }); });
attendanceRouter.post("/sessions/:id/rotate", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); const session = (db.attendanceSessions || []).find((i) => i.id === req.params.id); if (!session || (req.user.role !== "admin" && session.createdBy !== req.user.id)) return res.status(404).json({ message: "Session not found." }); session.sequence++; session.qrToken = createQrToken(session.id, session.sequence); await writeDb(db); res.json({ session }); });
attendanceRouter.post("/check-in", requireAuth, async (req, res) => { if (req.user.role !== "student") return res.status(403).json({ message: "Only students can check in." }); const { sessionId, qrToken, latitude, longitude, accuracy, deviceFingerprint, nonce } = req.body || {}; if (!sessionId || !qrToken || !nonce) return res.status(400).json({ message: "sessionId, qrToken, and nonce are required." }); const db = await readDb(); db.attendanceNonces ||= {}; const session = (db.attendanceSessions || []).find((i) => i.id === sessionId); if (!session || !session.active || session.qrToken !== qrToken) return res.status(409).json({ message: "QR code expired or invalid." }); if (db.attendanceNonces[nonce]) return res.status(409).json({ message: "This check-in has already been used." }); if (!timeInWindow(session)) return res.status(409).json({ message: "This attendance session is outside its time window." }); const subject = db.subjects.find((i) => i.id === session.subjectId); const student = db.students.find((i) => i.id === req.user.id); if (!student || student.className !== subject?.className) return res.status(403).json({ message: "You are not enrolled in this class." }); let location = null; let locationVerified = false; try { location = isWithinCollege(Number(latitude), Number(longitude), accuracy); locationVerified = location.withinRange; } catch { locationVerified = false; } if (!locationVerified) return res.status(403).json({ message: "Location verification failed. Please enable campus geolocation." }); const riskLevel = deviceFingerprint && db.deviceFingerprints?.[req.user.id] && db.deviceFingerprints[req.user.id] !== deviceFingerprint ? "high" : Number(accuracy) > 100 ? "medium" : "low"; db.deviceFingerprints ||= {}; db.deviceFingerprints[req.user.id] = deviceFingerprint || db.deviceFingerprints[req.user.id] || null; db.attendanceNonces[nonce] = { studentId: req.user.id, sessionId, usedAt: new Date().toISOString() }; const late = Date.now() > new Date(session.startsAt).getTime() + session.lateAfterMinutes * 60000; const result = upsertAttendance(db, { studentId: req.user.id, subjectId: session.subjectId, status: late ? "late" : "present", method: "qr-geofence", sessionId, locationVerified: true, riskLevel, deviceFingerprint }); if (riskLevel === "high") { db.attendanceReviewQueue ||= []; db.attendanceReviewQueue.unshift({ id: makeId("review"), attendanceId: result.record.id, reason: "device-risk", severity: "high", status: "open", createdAt: new Date().toISOString() }); } await writeDb(db); res.status(201).json({ record: enrichAttendance([result.record], db)[0], location: { distance: location.distance, radiusMeters: location.radiusMeters }, riskLevel }); });

attendanceRouter.get("/dashboard", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); const records = req.user.role === "teacher" ? (db.attendance || []).filter((i) => studentIdsVisibleToTeacher(db, req.user.code).has(i.studentId)) : (db.attendance || []); const analytics = attendanceAnalytics(db, records); const lowAttendance = db.students.filter((s) => { const stats = calculateStudentStats(s.id, records); return stats.total >= 3 && stats.percentage < 75; }).map((s) => ({ ...s, stats: calculateStudentStats(s.id, records) })); const queue = (db.attendanceReviewQueue || []).filter((i) => i.status === "open"); res.json({ analytics, lowAttendance, reviewQueue: queue, totals: { records: records.length, sessions: (db.attendanceSessions || []).length, exceptions: queue.length } }); });
attendanceRouter.get("/review-queue", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); res.json({ queue: db.attendanceReviewQueue || [] }); });
attendanceRouter.patch("/review-queue/:id", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); const item = (db.attendanceReviewQueue || []).find((i) => i.id === req.params.id); if (!item) return res.status(404).json({ message: "Review item not found." }); item.status = ["open", "resolved", "dismissed"].includes(req.body?.status) ? req.body.status : item.status; item.resolvedBy = req.user.id; item.resolvedAt = new Date().toISOString(); await writeDb(db); res.json({ item }); });
attendanceRouter.post("/corrections", requireAuth, async (req, res) => { const { attendanceId, requestedStatus, reason } = req.body || {}; const db = await readDb(); const record = (db.attendance || []).find((i) => i.id === attendanceId); if (!record || !ATTENDANCE_STATUSES.includes(requestedStatus) || !reason) return res.status(400).json({ message: "attendanceId, requestedStatus, and reason are required." }); if (req.user.role === "student" && record.studentId !== req.user.id) return res.status(403).json({ message: "You can only correct your own attendance." }); db.attendanceCorrections ||= []; const correction = { id: makeId("correction"), attendanceId, requestedStatus, reason: String(reason).slice(0, 500), requestedBy: req.user.id, status: "pending", createdAt: new Date().toISOString() }; db.attendanceCorrections.unshift(correction); await writeDb(db); res.status(201).json({ correction }); });
attendanceRouter.get("/audit", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); const ids = req.query.studentId ? new Set((db.attendance || []).filter((i) => i.studentId === req.query.studentId).map((i) => i.id)) : null; res.json({ audit: (db.attendanceAudit || []).filter((i) => !ids || ids.has(i.attendanceId)).slice(0, 500) }); });
attendanceRouter.get("/export.csv", requireAuth, requireStaff, async (req, res) => { const db = await readDb(); let records = db.attendance || []; if (req.user.role === "teacher") { const visible = studentIdsVisibleToTeacher(db, req.user.code); records = records.filter((i) => visible.has(i.studentId)); } if (req.query.date) records = records.filter((i) => i.date === req.query.date); res.header("Content-Type", "text/csv"); res.attachment("attendance-report.csv"); res.send(attendanceCsv(records, db)); });
