import React, { useEffect, useState } from "react";
import { Bell, CheckCheck, X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { apiFetch } from "../context/api.js";

const POLL_MS = 30000;
const labels = { notice: "Notice", assignment: "Assignment", exam: "Exam", attendance: "Attendance", result: "Result", security: "Security" };
function relativeTime(value) { const delta = Math.max(0, Date.now() - new Date(value).getTime()); const minutes = Math.floor(delta / 60000); if (minutes < 1) return "Just now"; if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); if (hours < 24) return `${hours}h ago`; return `${Math.floor(hours / 24)}d ago`; }
export function NotificationCenter() { const navigate = useNavigate(); const [data, setData] = useState({ notifications: [], unreadCount: 0 }); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false);
  async function load() { try { setLoading(true); setData(await apiFetch("/shared/notifications")); } finally { setLoading(false); } }
  useEffect(() => { load(); const timer = setInterval(load, POLL_MS); return () => clearInterval(timer); }, []);
  async function markRead(item) { if (!item.read) { await apiFetch(`/shared/notifications/${encodeURIComponent(item.id)}/read`, { method: "POST" }); await load(); } if (item.href) { setOpen(false); navigate(item.href); } }
  async function markAll() { await apiFetch("/shared/notifications/read-all", { method: "POST" }); await load(); }
  return <div className="notification-center"><button className="topbar-bell icon-button" type="button" aria-label="Open notifications" aria-expanded={open} onClick={() => setOpen((value) => !value)}><Bell size={18} />{data.unreadCount > 0 && <span className="notification-count">{data.unreadCount > 99 ? "99+" : data.unreadCount}</span>}</button>{open && <><button className="notification-dismiss" aria-label="Close notifications" onClick={() => setOpen(false)} /><div className="notification-popover"><div className="notification-head"><div><strong>Notifications</strong><span>{data.unreadCount ? `${data.unreadCount} unread` : "All caught up"}</span></div><div className="notification-head-actions"><button className="ghost-button small" type="button" onClick={markAll} disabled={!data.unreadCount}><CheckCheck size={15} /> Mark all read</button><button className="ghost-button small" type="button" onClick={() => setOpen(false)} aria-label="Close"><X size={15} /></button></div></div>{loading && <div className="notification-empty">Loading notifications…</div>}{!loading && !data.notifications.length && <div className="notification-empty">No notifications yet.</div>}<div className="notification-list">{data.notifications.map((item) => <button type="button" key={item.id} className={`notification-item ${item.read ? "read" : "unread"}`} onClick={() => markRead(item)}><span className={`notification-dot ${item.category}`} /><span className="notification-copy"><strong>{item.title}</strong><small>{labels[item.category] || item.category} · {relativeTime(item.createdAt)}</small><span>{item.body}</span></span>{!item.read && <span className="unread-mark" />}</button>)}</div></div></>}</div>; }
