import React, { useEffect, useState } from "react";
import { LogOut, Monitor, ShieldCheck, Smartphone } from "lucide-react";
import { apiFetch } from "../context/api.js";

function deviceIcon(value) { return /mobile|android|iphone|ipad/i.test(value) ? <Smartphone size={18} /> : <Monitor size={18} />; }
export function SessionManagement() { const [sessions, setSessions] = useState([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { try { setLoading(true); const data = await apiFetch("/auth/sessions"); setSessions(data.sessions || []); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function revoke(sessionId) { try { await apiFetch(`/auth/sessions/${encodeURIComponent(sessionId)}/revoke`, { method: "POST" }); setMessage("Session signed out."); await load(); } catch (err) { setError(err.message); } }
  async function logoutOthers() { try { const data = await apiFetch("/auth/sessions/logout-others", { method: "POST" }); setMessage(`${data.revoked} other session${data.revoked === 1 ? "" : "s"} signed out.`); await load(); } catch (err) { setError(err.message); } }
  return <section className="panel session-panel"><div className="section-heading"><div><span className="eyebrow">Session security</span><h2>Active sessions</h2><p className="helper-text">Review where your account is signed in. Only coarse network information is shown.</p></div><ShieldCheck size={21} /></div>{message && <div className="success-box">{message}</div>}{error && <div className="error-box">{error}</div>}{loading ? <p className="helper-text">Loading sessions…</p> : !sessions.length ? <p className="helper-text">No active sessions found.</p> : <div className="list-stack">{sessions.map((session) => <div className="session-row list-row" key={session.sessionId}><div className="session-device-icon">{deviceIcon(session.userAgent)}<div><strong>{session.device}</strong><span>{session.userAgent}</span><span>{session.ip ? `Network: ${session.ip}` : "Network address unavailable"} · Last active {new Date(session.lastActiveAt).toLocaleString()}</span></div></div><div className="action-row">{session.current ? <span className="current-session"><span className="status-dot" />Current session</span> : <button className="secondary-button danger-text" type="button" onClick={() => revoke(session.sessionId)}><LogOut size={15} /> Sign out</button>}</div></div>)}</div>}{sessions.filter((session) => !session.current).length > 0 && <button className="secondary-button" type="button" onClick={logoutOthers} style={{ marginTop: 14 }}><LogOut size={16} /> Sign out other sessions</button>}</section>; }
